      - name: Container image scan
        uses: Azure/container-scan@v0.1
        with:
        # Docker image to scan
        image-name:  ubuntu-latest
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        severity-threshold: HIGH
        # Username to authenticate to the Docker registry
        # Github token
        token: # default is ${{ github.token }}
        # Add additional checks to ensure the image is secure and follows best practices and CIS standards
        run-quality-checks: # optional, default is true
